'use client';

import { useState } from 'react';
import {
  ArrowDownRight, ArrowRight, ChartNoAxesCombined, Check, ClipboardList,
  Database, Gauge, Package, RotateCcw, ShoppingCart, Sparkles, TriangleAlert,
} from 'lucide-react';
import styles from './intelligence.module.css';

// Fixed illustrative inputs. Arithmetic is deterministic, not generated by an LLM.
const sample = { usualSales: 1000, thursdaySales: 860, usualDinnerOrders: 50, dinnerOrders: 36, chickenKg: 18, projectedDemandKg: 24 };
const salesChange = Math.round((sample.thursdaySales / sample.usualSales - 1) * 100);
const suggestedPurchaseKg = Math.max(0, sample.projectedDemandKg - sample.chickenKg);
const pounds = (value: number) => `£${value.toLocaleString('en-GB')}`;

export function IntelligenceDemo() {
  const [draftCreated, setDraftCreated] = useState(false);

  return (
    <div className={styles.workspace}>
      <div className={styles.workspaceBar}>
        <div><Sparkles aria-hidden="true" /><strong>Intelligence workspace</strong></div>
        <span className={styles.sampleBadge}>ILLUSTRATIVE DEMO · SAMPLE DATA</span>
      </div>
      <div className={styles.workspaceGrid}>
        <aside className={styles.dataPanel} aria-labelledby="sample-data-title">
          <p className={styles.smallLabel}><Database aria-hidden="true" />THE DATA BEHIND THE BRIEF</p>
          <h3 id="sample-data-title">Thursday, in context.</h3>
          <p className={styles.dataIntro}>A sample service review, looking ahead to Friday.</p>
          <div className={styles.salesSignal}>
            <span>Sales vs usual Thursday</span>
            <strong><ArrowDownRight aria-hidden="true" />{salesChange}%</strong>
            <div className={styles.barRow}><span>Usual</span><div><i style={{ width: '100%' }} /></div><b>{pounds(sample.usualSales)}</b></div>
            <div className={styles.barRow}><span>Thursday</span><div><i style={{ width: `${sample.thursdaySales / sample.usualSales * 100}%` }} /></div><b>{pounds(sample.thursdaySales)}</b></div>
            <p>Calculated from sample sales totals.</p>
          </div>
          <dl className={styles.sourceRows}>
            <div><dt><ClipboardList aria-hidden="true" />Dinner orders · 7–9 PM</dt><dd>{sample.dinnerOrders} <span>vs {sample.usualDinnerOrders} usual</span></dd></div>
            <div><dt><Package aria-hidden="true" />Chicken on hand</dt><dd>{sample.chickenKg} kg <span>stock record</span></dd></div>
            <div><dt><ChartNoAxesCombined aria-hidden="true" />Demand through Friday service</dt><dd>{sample.projectedDemandKg} kg <span>sample forecast input</span></dd></div>
          </dl>
          <div className={styles.dataNote}><Database aria-hidden="true" /><p>Sales and stock records feed the analytics. Intelligence explains the signals and recommends a next step.</p></div>
        </aside>

        <div className={styles.briefPanel}>
          <div className={styles.briefHeading}><div><p className={styles.smallLabel}>FRIDAY · MORNING BRIEF</p><h3>Here’s what needs your attention.</h3></div><span className={styles.briefMark}><Sparkles aria-hidden="true" /></span></div>
          <ol className={styles.story}>
            <li>
              <span className={styles.storyIcon}><ArrowDownRight aria-hidden="true" /></span>
              <div><p className={styles.stageLabel}>OBSERVATION</p><h4>Sales are down {Math.abs(salesChange)}% vs your usual Thursday.</h4><p>Yesterday’s sales finished below the usual Thursday total.</p></div>
            </li>
            <li>
              <span className={styles.storyIcon}><ChartNoAxesCombined aria-hidden="true" /></span>
              <div><p className={styles.stageLabel}>REASON</p><h4>Dinner order volume between 7–9 PM was lower than usual.</h4><p>{sample.dinnerOrders} orders compared with {sample.usualDinnerOrders} in the sample baseline. A quieter dinner service helps explain the change.</p></div>
            </li>
            <li>
              <span className={`${styles.storyIcon} ${styles.warning}`}><TriangleAlert aria-hidden="true" /></span>
              <div><p className={styles.stageLabel}>PREDICTION</p><h4>Chicken stock is projected to run out before Friday evening service.</h4><p>Looking ahead, a separate stock check flags {sample.chickenKg} kg on hand against {sample.projectedDemandKg} kg of projected demand through service.</p></div>
            </li>
            <li className={styles.recommendation}>
              <span className={styles.storyIcon}><ShoppingCart aria-hidden="true" /></span>
              <div><p className={styles.stageLabel}>RECOMMENDATION</p><h4>Increase the next chicken purchase.</h4><p>Consider {suggestedPurchaseKg} kg based on projected demand and current stock. Review delivery timing before ordering.</p>
                <div className={styles.actionArea}>
                  <button className={`button ${draftCreated ? 'button-secondary' : 'button-primary'} ${styles.actionButton}`} onClick={() => setDraftCreated(!draftCreated)}>
                    {draftCreated ? <><RotateCcw aria-hidden="true" />Reset demonstration</> : <>Create Purchase Order<ArrowRight aria-hidden="true" /></>}
                  </button>
                  <p>Sample action only. No order is sent.</p>
                </div>
                <div role="status" aria-live="polite" aria-atomic="true">
                  {draftCreated && <div className={styles.draftConfirmation}><Check aria-hidden="true" /><div><strong>Sample purchase order draft created</strong><p>Chicken · {suggestedPurchaseKg} kg. Awaiting owner review; supplier and delivery date still to be confirmed.</p></div></div>}
                </div>
              </div>
            </li>
            <li>
              <span className={styles.storyIcon}><Gauge aria-hidden="true" /></span>
              <div><p className={styles.stageLabel}>MEASURE</p><h4>{draftCreated ? 'Draft ready. Outcome still pending.' : 'Follow the action through to service.'}</h4><p>After delivery, compare stock received, actual usage and any stock-outs with the forecast. No outcome has been recorded in this demo.</p></div>
            </li>
          </ol>
        </div>
      </div>
    </div>
  );
}
