import { ArrowUpRight, Bell, ChartNoAxesCombined, Check, ChevronDown, ChefHat, CircleHelp, LayoutDashboard, Package, PanelLeftClose, Search, ShoppingCart, Sparkles, Terminal, TriangleAlert, Users, UtensilsCrossed } from 'lucide-react';
const modules = [{ icon: Terminal, label: 'POS' }, { icon: ChefHat, label: 'Kitchen' }, { icon: Package, label: 'Inventory' }, { icon: Users, label: 'Customers' }];
export function ProductPreview() {
  return <figure className="product-preview" aria-label="Illustrative Qavyo restaurant dashboard with sample operational data and Intelligence recommendations">
    <div className="preview-overline"><span className="preview-line" />YOUR OPERATION. CONNECTED.<span className="sample-label">ILLUSTRATIVE PREVIEW</span></div>
    <div className="dashboard"><aside className="dashboard-sidebar" aria-hidden="true"><span className="mini-brand">q.</span><LayoutDashboard className="selected" /><Terminal /><ChefHat /><Package /><Users /><span className="sidebar-bottom"><CircleHelp /><PanelLeftClose /></span></aside>
      <div className="dashboard-body"><div className="dashboard-topbar"><span><UtensilsCrossed />Your restaurant<ChevronDown /></span><div><Search /><Bell /><span className="avatar">Q</span></div></div>
        <div className="dashboard-content"><div className="dashboard-title"><div><span className="interface-kicker">WORKSPACE OVERVIEW</span><h2>Ready for service.</h2></div><span className="today">Today<ChevronDown aria-hidden="true" /></span></div>
          <div className="module-grid">{modules.map(({ icon: Icon, label }) => <div key={label}><Icon aria-hidden="true" /><span>{label}</span><span className="module-status"><span />Connected</span></div>)}</div>
          <div className="service-panel"><div className="panel-title"><h3>Service overview</h3><span>Sample workspace</span></div><div className="order-columns">{[{ label: 'New orders', name: 'Table 04', detail: 'Dine-in · 2 items', status: 'Received' }, { label: 'In the kitchen', name: 'Table 08', detail: 'Dine-in · 3 items', status: 'Preparing' }, { label: 'Ready to serve', name: 'Table 02', detail: 'Dine-in · 2 items', status: 'Ready' }].map(order => <div className="order-column" key={order.label}><span>{order.label}</span><div className="order-card"><UtensilsCrossed aria-hidden="true" /><strong>{order.name}</strong><small>{order.detail}</small><span className="order-status">{order.status}</span></div></div>)}</div></div>
          <div className="connection-note"><Check aria-hidden="true" />One workspace, from front of house to back of house.</div>
        </div>
      </div>
    </div>
    <div className="intelligence-composition"><article className="daily-brief"><div className="brief-top"><span className="intelligence-icon"><Sparkles aria-hidden="true" /></span><span>QAVYO INTELLIGENCE</span><span className="brief-sample">SAMPLE</span></div><h3>Your Daily Brief</h3><p>A clearer view of the day ahead.</p><div className="brief-rule" /><div className="brief-summary"><Check aria-hidden="true" /><span>Service, stock and sales.<br /><strong>The details, brought together.</strong></span></div><span className="brief-bottom">Built around your restaurant<ArrowUpRight aria-hidden="true" /></span></article>
    <div className="insight-stack"><article className="insight-card"><span className="insight-icon warning"><TriangleAlert aria-hidden="true" /></span><div><h3>Stock Alert</h3><p>Tomatoes are below the sample par level.</p></div></article><article className="insight-card"><span className="insight-icon"><ChartNoAxesCombined aria-hidden="true" /></span><div><h3>Sales Insight</h3><p>Explore sales by service and menu item.</p></div></article><article className="insight-card"><span className="insight-icon success"><ShoppingCart aria-hidden="true" /></span><div><h3>Purchase Recommendation</h3><p>Review tomatoes for your next supplier order.</p></div></article></div></div>
    <figcaption><span aria-hidden="true" />Restaurant operations + Qavyo Intelligence</figcaption>
  </figure>;
}
